# Generated by Django 5.2.5 on 2025-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_first_name_voter_grade_level_voter_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
