# Generated by Django 5.2.5 on 2025-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_title_position_name_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
