# Generated by Django 5.2.5 on 2025-10-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_party_candidate_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
