# Generated by Django 5.2.8 on 2025-11-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_vote_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.RemoveField(
            model_name='party',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='party',
            name='theme',
        ),
        migrations.AddField(
            model_name='party',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_of', to='voting.candidate'),
        ),
        migrations.AddField(
            model_name='party',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_of', to='voting.candidate'),
        ),
        migrations.AddField(
            model_name='party',
            name='team_name',
            field=models.CharField(blank=True, help_text='Team name (e.g., Team Galing, Team Sigla)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='vice_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president_of', to='voting.candidate'),
        ),
    ]
