# Generated by Django 5.2.8 on 2025-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='rules',
            field=models.TextField(blank=True, help_text='Team rules and guidelines', null=True),
        ),
    ]
